name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: 'Install system dependencies'
      if: runner.os == 'Linux'
      run: |
        sudo apt update
        sudo apt-get update
        sudo apt-get -y install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libgl1-mesa-dev
        sudo apt-get -y install build-essential libx11-dev libglfw3-dev libglfw3 xorg-dev
    - name: 'Install Norminette'
      if: runner.os == 'Linux'
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install norminette
    - uses: actions/checkout@v3
    - name: make
      run: make
  norminette_job:
    runs-on: ubuntu-latest
    name: norminette
    steps:
    - uses: actions/checkout@v2
    - uses: alexandregv/norminette-action@v3
      with:
        flags: 'srcs/*.c includes/*.h'