name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  statuses: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Install system dependencies'
      if: runner.os == 'Linux'
      run: |
        sudo apt update
        sudo apt-get update
        sudo apt-get -y install build-essential libx11-dev xorg-dev
        sudo apt-get -y install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libgl1-mesa-dev
    - uses: actions/checkout@v3
    - name: make
      run: make
    - name: 'Test maps'
      run: make test
  norminette_job:
    runs-on: ubuntu-latest
    name: norminette
    steps:
    - uses: actions/checkout@v2
    - uses: alexandregv/norminette-action@v3
      with:
        flags: 'src/*.c include/*.h'